<a href="https://colab.research.google.com/github/dpersa06/Dave-/blob/master/tensorflowDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
#Constant Tensor
a = tf.constant([[1,2],[3,4]])

In [5]:
#Variable Tensor 
b = tf.Variable([[5,6], [7,8]])
 

In [6]:
#Print both tensors
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>


In [9]:
#Concatenate tensors a and b: axis=0 is rows, axis=1 is columns
ab_concat = tf.concat(values = [a,b], axis = 1)
ab_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [13]:
#Create a tensor of zeros or ones
tensor0 = tf.zeros(shape = [4,4], dtype = tf.float32)
print(tensor0)

tensor1 = tf.ones(shape = [4,4], dtype = tf.float32)
tensor1

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Typecast a tensor: convert from one date type to another
tensor_float = tf.constant([[1.1,1.2,1.3,1.4], 
                      [2.1,2.2,2.3,2.4],
                      [3.1,3.2,3.3,3.4],
                      [4.1,4.2,4.3,4.4]],
                     dtype = tf.float32)
tensor_int = tf.cast(tensor_float, tf.int32)

print(tensor_float)
print(tensor_int)


tf.Tensor(
[[1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]
 [3.1 3.2 3.3 3.4]
 [4.1 4.2 4.3 4.4]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]], shape=(4, 4), dtype=int32)


In [ ]:
#Transpose a tensor
a = tf.transpose(tensor_int)
a


In [19]:
#Multiplication
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[1,2], [3,4]])

mult = tf.matmul(a, b)
mult

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>